services:
  - type: web
    name: promed-backend
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://aws-0-ap-south-1.pooler.supabase.com:5432/postgres?sslmode=require
      - key: SPRING_DATASOURCE_USERNAME
        value: postgres.eclxsguomhhelpjxmvon
      - key: SPRING_DATASOURCE_PASSWORD
        value: Wahaguruji$1313
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update
      - key: SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_SCHEMA
        value: public
      - key: SPRING_MAIL_HOST
        value: ""

